<?xml version="1.0" encoding="utf-8"?><Database Name="CheeseTrackerDb" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Daniel\Documents\GitHub\DVo-MidwayUSA\CheeseTracker\CheeseTracker\CheeseTracker.AspNetMvc.App\App_Data\CheeseTrackerDb.mdf;Integrated Security=True" SettingsObjectName="CheeseTracker.Common.DataAccess.Properties.Settings" SettingsPropertyName="CheeseTrackerDbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CheeseData" Member="CheeseDatas">
    <Type Name="CheeseData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>